In [1]:
#Vectors

In [2]:
height_weight_age = [70, # inches,
170, # pounds,
40 ] # years

In [3]:
height_weight_age

[70, 170, 40]

In [4]:
grades = [95, # exam1
80, # exam2
75, # exam3
62 ] # exam4

In [5]:
grades

[95, 80, 75, 62]

In [6]:
#One problem with this approach is that we will want to perform arithmetic on vectors.
#Because Python lists aren’t vectors (and hence provide no facilities for vector arithmetic),
#we’ll frequently need to add two vectors. Vectors add componentwise. This
#means that if two vectors v and w are the same length, their sum is just the vector whose
#first element is v[0] + w[0], whose second element is v[1] + w[1], and so on. (If they’re
#not the same length, then we’re not allowed to add them.)
#For example, adding the vectors [1, 2] and [2, 1] results in [1 + 2, 2 + 1] or [3, 3],

In [7]:
# We can easily implement this by zip-ing the vectors together and using a list
# comprehension to add the corresponding elements:

In [9]:
def vector_add(v, w):
    """adds corresponding elements"""
    return [v_i + w_i for v_i, w_i in zip(v, w)]

In [11]:
def vector_subtract(v, w):
    """subtracts corresponding elements"""
    return [v_i - w_i for v_i, w_i in zip(v, w)]

In [12]:
# We’ll also sometimes want to componentwise sum a list of vectors. That is, create a new
# vector whose first element is the sum of all the first elements, whose second element is the
# sum of all the second elements, and so on. The easiest way to do this is by adding one
# vector at a time:

In [13]:
def vector_sum(vectors):
    """sums all corresponding elements"""
    result = vectors[0] # start with the first vector
    for vector in vectors[1:]: # then loop over the others
        result = vector_add(result, vector) # and add them to the result
    return result

In [14]:
#If you think about it, we are just reduce-ing the list of vectors using vector_add, which
#means we can rewrite this more briefly using higher-order functions:
def vector_sum(vectors):
    return reduce(vector_add, vectors)

In [22]:
from functools import partial
from functools import reduce#or even:
vector_sum = partial( reduce , vector_add)

In [23]:
from functools import partial

def multiply(x,y):
        return x *(1+y)

# create a new function that multiplies by 2 for y or if not specified will be x 
dbl = partial(multiply,y=2)
print(dbl(4))

12


In [24]:
# python code to demonstrate summation  
# using reduce() and accumulate() 
  
# importing itertools for accumulate() 
import itertools 
  
# importing functools for reduce() 
import functools 
  
# initializing list  
lis = [ 1, 3, 4, 10, 4 ] 
  
# priting summation using accumulate() 
print ("The summation of list using accumulate is :",end="") 
print (list(itertools.accumulate(lis,lambda x,y : x+y))) 
  
# priting summation using reduce() 
print ("The summation of list using reduce is :",end="") 
print (functools.reduce(lambda x,y:x+y,lis)) 

The summation of list using accumulate is :[1, 4, 8, 18, 22]
The summation of list using reduce is :22


In [25]:
def scalar_multiply(c, v):
    """c is a number, v is a vector"""
    return [c * v_i for v_i in v]

In [26]:
def vector_mean(vectors):
    """compute the vector whose ith element is the mean of the
    ith elements of the input vectors"""
    n = len(vectors)
    return scalar_multiply(1/n, vector_sum(vectors))

In [27]:
#the dot product

In [28]:
def dot(v, w):
    """v_1 * w_1 + ... + v_n * w_n"""
    return sum(v_i * w_i for v_i, w_i in zip(v, w))

# The dot product measures how far the vector v extends in the w direction. For example, if
# w = [1, 0] then dot(v, w) is just the first component of v. Another way of saying this is
# that it’s the length of the vector you’d get if you projected v onto w

In [29]:
#Using this, it’s easy to compute a vector’s sum of squares:
def sum_of_squares(v):
    """v_1 * v_1 + ... + v_n * v_n"""
    return dot(v, v)

In [30]:
#Which we can use to compute its magnitude (or length):

In [31]:
import math
def magnitude(v):
    return math.sqrt(sum_of_squares(v)) # math.sqrt is square root function

In [32]:
def squared_distance(v, w):
    """(v_1 - w_1) ** 2 + ... + (v_n - w_n) ** 2"""
    return sum_of_squares(vector_subtract(v, w))

In [33]:
def distance(v, w):
    return math.sqrt(squared_distance(v, w))

In [34]:
#clearer 

In [35]:
def distance(v, w):
    return magnitude(vector_subtract(v, w))

In [36]:
# #Using lists as vectors is great for exposition but terrible for performance.
# In production code, you would want to use the NumPy library, which includes a high-performance array
# class with all sorts of arithmetic operations included.

In [37]:
# Matrices

In [38]:
#A matrix is a two-dimensional collection of numbers. We will represent matrices as lists
#of lists,

In [39]:
A = [[1, 2, 3], # A has 2 rows and 3 columns
[4, 5, 6]]
B = [[1, 2], # B has 3 rows and 2 columns
[3, 4],
[5, 6]]

In [40]:
A


[[1, 2, 3], [4, 5, 6]]

In [42]:
# In mathematics, you would usually name the first row of the matrix “row 1” and the first column “column
# 1.” Because we’re representing matrices with Python lists, which are zero-indexed, we’ll call the first row
# of a matrix “row 0” and the first column “column 0.”

In [44]:
def shape(A):
    num_rows = len(A)
    num_cols = len(A[0]) if A else 0 # number of elements in first row
    return num_rows, num_cols

In [45]:
def get_row(A, i):
    return A[i] # A[i] is already the ith row


def get_column(A, j):
    return [A_i[j]  for A_i in A]            # jth element of row A_i
            # for each row A_i

In [46]:
#We’ll also want to be able to create a matrix given its shape and a function for generating
#its elements. We can do this using a nested list comprehension:
def make_matrix(num_rows, num_cols, entry_fn):
    """returns a num_rows x num_cols matrix
    whose (i,j)th entry is entry_fn(i, j)"""
    return [[entry_fn(i, j) # given i, create a list
        for j in range(num_cols)] # [entry_fn(i, 0), ... ]
        for i in range(num_rows)] # create one list for each i

In [47]:
def is_diagonal(i, j):
    """1's on the 'diagonal', 0's everywhere else"""
    return 1 if i == j else 0

In [48]:
identity_matrix = make_matrix(5, 5, is_diagonal)

In [49]:
identity_matrix

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

In [50]:
data = [[70, 170, 40],
[65, 120, 26],
[77, 250, 19],
# ....
]

In [51]:
data

[[70, 170, 40], [65, 120, 26], [77, 250, 19]]

In [52]:
#Recall that before we had:
friendships = [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4),
(4, 5), (5, 6), (5, 7), (6, 8), (7, 8), (8, 9)]

In [53]:
friendships

[(0, 1),
 (0, 2),
 (1, 2),
 (1, 3),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (5, 7),
 (6, 8),
 (7, 8),
 (8, 9)]

In [55]:
#We could also represent this as:
# user 0 1 2 3 4 5 6 7 8 9
#
friendships = [[0, 1, 1, 0, 0, 0, 0, 0, 0, 0], # user 0
[1, 0, 1, 1, 0, 0, 0, 0, 0, 0], # user 1
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0], # user 2
[0, 1, 1, 0, 1, 0, 0, 0, 0, 0], # user 3
[0, 0, 0, 1, 0, 1, 0, 0, 0, 0], # user 4
[0, 0, 0, 0, 1, 0, 1, 1, 0, 0], # user 5
[0, 0, 0, 0, 0, 1, 0, 0, 1, 0], # user 6
[0, 0, 0, 0, 0, 1, 0, 0, 1, 0], # user 7
[0, 0, 0, 0, 0, 0, 1, 1, 0, 1], # user 8
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]] # user 9

In [56]:
friendships


[[0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]]

In [57]:
friendships[0][2] == 1 # True, 0 and 2 are friends
friendships[0][8] == 1 # False, 0 and 8 are not friends

False

In [58]:
friends_of_five = [i # only need
for i, is_friend in enumerate(friendships[5]) # to look at
if is_friend]

In [59]:
friends_of_five

[4, 6, 7]

In [4]:
#difference between numpy dot() and inner()
#What's difference between numpy dot() and inner()?
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [5]:
np.inner(a,b)

array([[35, 41],
       [81, 95]])

In [6]:
>>> import numpy as np
>>> A = np.matrix([[1.,2], [3,4], [5,6]])
>>> A


matrix([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [8]:
>>> B = np.matrix("1.,2; 3,4; 5,6")
>>> B


matrix([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [9]:
>>> x = np.matrix("10., 20.")
>>> x

matrix([[10., 20.]])

In [10]:
x.T

matrix([[10.],
        [20.]])

In [11]:
>>> x = np.matrix("10., 20.")
>>> x

matrix([[10., 20.]])

In [12]:
x.T

matrix([[10.],
        [20.]])

In [14]:
x = np.matrix("4.;5.")
x

matrix([[4.],
        [5.]])

In [22]:
>>> A = np.matrix([[1.,2], [3,4], [5,6]])
>>> A


matrix([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [23]:
 A*x

matrix([[14.],
        [32.],
        [50.]])

In [24]:
>>> print (x[0,0], x[1,0])

4.0 5.0


In [25]:
>>> import numpy as np
>>> A = np.ones((4,3))
>>> A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.rank(A)#Note that the rank of the array is not the rank of the matrix in linear algebra (dimension of the column space) but the number of subscripts it takes!

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  """Entry point for launching an IPython kernel.


2

In [27]:
np.ndim(A)

2

In [31]:
#Scalars have rank 0:

x = np.array(10)
x

np.rank(x)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  


0

In [32]:
np.ndim(x)

0

In [33]:
#NumPy supports arrays of any dimension such as rank 3 (2x2x2):



In [34]:
>>> A = np.ones((2,2,2))
>>> A

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [35]:
>>> A[1,0,1]

1.0

In [36]:
>>> A = np.array([[1,2],[3,4]])
>>> A

array([[1, 2],
       [3, 4]])

In [37]:
>>> b = np.array([10, 20])
>>> b

array([10, 20])

In [38]:
>>> ans = np.dot(A,b)
>>> ans

array([ 50, 110])

In [39]:
>>> A = np.array([[ 1, 2 ,3], [ 4, 5 ,6]])
>>> B = np.array([7,8,9])
>>> 
>>> A

>>> 
>>> B

>>> 
>>> A.shape
>>> B.shape
>>> 
>>> A.T
       
>>> 
>>> B.T
>>> 
>>> A.dot(B)
>>> 
>>> np.dot(A,B)


array([ 50, 122])

In [40]:
#Ax = b : numpy.linalg

In [41]:
import numpy as np

In [42]:
from numpy.linalg import solve

In [43]:
A = np.array([[1,2],[3,4]])

In [44]:
A

array([[1, 2],
       [3, 4]])

In [45]:
b = np.array([10, 20])

In [46]:
b

array([10, 20])

In [47]:
x = solve(A,b)

In [48]:
x

array([0., 5.])

In [49]:
#eigen values and vectors


In [51]:
>>> import numpy as np
>>> from numpy.linalg import eig
>>> A = np.array([[1,2],[3,4]])
>>> eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [52]:
#The eig returns two tuples: the first one is the eigen values and the second one is a matrix whose columns are the two eigen vectors.

In [53]:
>>> eigen_val, eigen_vec = eig(A)
>>> eigen_val

array([-0.37228132,  5.37228132])

In [54]:
>>> eigen_vec

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [56]:
# Quadrature
# We want to solve 
# ∫
# 3
# 0
# x
# 4
# d
# x
# =
# 243
# 4
# :

from scipy.integrate import quad
def f(x):
    return x**4
 
quad(f, 0., 3.)

#The returned tuple indicates (ans, error estimate).

#We can get the same answer if we use lambda instead:

quad(lambda x: x**4, 0, 3)
#(48.599999999999994, 5.39568389967826e-13)

(48.599999999999994, 5.39568389967826e-13)

In [57]:
#summary 

In [59]:
a=np.zeros((2,2))

In [60]:
b=np.ones((2,2))

In [61]:
c=np.full((2,2),7)

In [63]:
d=np.eye(2)

In [64]:
e=np.random.random((2,2))

In [65]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])
M = np.vstack([v1, v2, v3])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
## There is also a way to do this horizontally => hstack

In [68]:
M[:2, 1:3]#exlusive

array([[2, 3],
       [5, 6]])

In [82]:
import numpy as np

v=np.matrix([[1],[2],[3]])

In [83]:
v


matrix([[1],
        [2],
        [3]])

In [84]:
 M.dot(v)
    

matrix([[14],
        [32],
        [50]])

In [86]:
 #v.dot(v) ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [90]:
 v.T.dot(v)#transposing and then dotting will yeild a scalar 

matrix([[14]])

In [91]:
v.T

matrix([[1, 2, 3]])

In [94]:
#Cross Multiplication
np.cross(v1, v2, axisa=0, axisb=0).T

array([-3,  6, -3])

In [96]:
M=np.matrix([[3,0,2],[2,0,-2],[0,1,1]])

In [97]:
M

matrix([[ 3,  0,  2],
        [ 2,  0, -2],
        [ 0,  1,  1]])

In [98]:
v=np.matrix([[1],[2],[3]])

In [100]:
np.multiply(M,v)#M=np.matrix([[3,0,2],[2,0,-2],[0,1,1]])

matrix([[ 3,  0,  2],
        [ 4,  0, -4],
        [ 0,  3,  3]])

In [101]:
np.multiply(v, v)

matrix([[1],
        [4],
        [9]])

In [102]:
 M.T

matrix([[ 3,  2,  0],
        [ 0,  0,  1],
        [ 2, -2,  1]])

In [103]:
v.T

matrix([[1, 2, 3]])

In [104]:
M.T.shape , v.T.shape

((3, 3), (1, 3))

In [105]:
np.linalg.inv(M) #Determinant and Inverse

matrix([[ 0.2,  0.2,  0. ],
        [-0.2,  0.3,  1. ],
        [ 0.2, -0.3, -0. ]])

In [106]:
np.linalg.det(M)

10.000000000000002

In [108]:
#Au=(lambdaa)u

In [109]:
#To define the solution of the above, (A-(lambdaa)*eye) u=0

In [3]:
M=np.matrix([[0,1], [-2, -3]])

In [4]:
M

matrix([[ 0,  1],
        [-2, -3]])

In [113]:
eigvals, eigvecs = np.linalg.eig(M)

In [114]:
eigvals

array([-1., -2.])

In [115]:
eigvecs

matrix([[ 0.70710678, -0.4472136 ],
        [-0.70710678,  0.89442719]])

In [116]:
# Please read the NumPy
# docs on this function before using
# it, lots more information about
# multiplicity of eigenvalues and etc
# there.

In [2]:
#https://www.youtube.com/watch?v=P5mlg91as1c

In [3]:
#https://web.stanford.edu/class/cs231a/section/section1.pdf

In [5]:
import numpy as np

U, S, Vtranspose = np.linalg.svd(M)

In [6]:
U

matrix([[-0.22975292,  0.97324899],
        [ 0.97324899,  0.22975292]])

In [7]:
S

array([3.70245917, 0.54018151])

In [8]:
Vtranspose

matrix([[-0.52573111, -0.85065081],
        [-0.85065081,  0.52573111]])